---
title: "Covid 19 Exploration Project"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


```{r read}
library(tidyverse)
covid19 <- read_csv("data/covid19-daily-cases.csv")
covid19
```



```{r graph}
covid19 %>% 
  ggplot(aes(
    x = date, 
    y = confirmed, 
    colour = country_region)) +
  geom_line() +
  guides(colour = FALSE)
```

```{r graph log}
# Fit with log scale so it becomes normal

covid19 %>% 
  ggplot(aes(
    x = date, 
    y = log10(confirmed),
    colour = country_region)) +
  geom_line() +
  guides(colour = FALSE)
```

```{r graph log scale}
#change scale for log
covid19 %>% 
  ggplot(aes(
    x = date, 
    y = confirmed, 
    colour = country_region)) +
  geom_line() +
  guides(colour = FALSE) +
  scale_y_log10()
```

```{r countries}
# sorting the data by countries
covid19_rel <- covid19 %>% 
  group_by(country_region) %>% 
  mutate(days = as.numeric(date - min(date))) %>% 
  ungroup()
covid19_rel
```

```{r region graph}
#graph for countries and days since march 1
world <- covid19_rel %>% 
  ggplot(aes(
    x = days,
    y = confirmed, 
    colour = country_region)) +
  geom_line() +
  scale_y_log10() +
  guides(colour = FALSE)
world
```
```{r nz}
# nz highlighted out of all countries
covid19_nz <- covid19_rel %>% 
  filter(country_region == "New Zealand")
p_nz <- covid19_rel %>% 
  ggplot(aes(x = days, y = confirmed, 
    group = country_region)) +
  geom_line(colour = "grey", alpha = 0.5) +
  geom_line(colour = "#238b45", size = 1, data = covid19_nz) +
  scale_y_log10() +
  guides(colour = FALSE)
p_nz
```

```{r graph nz}
#changed labels
p_nz <- p_nz +
  geom_label(aes(
    x = max(days), y = max(confirmed),
    label = country_region), data = covid19_nz,
    colour = "#238b45", nudge_x = 3, nudge_y = .5)
p_nz
```
```{r graph nz scale}
p_nz <- p_nz +
  scale_y_log10(labels = scales::label_comma()) +
  xlim(c(0, 100))
p_nz
```

```{r graph nz scale labels}
p_nz <- p_nz +
  labs(
    x = "Days since March 1",
    y = "Confirmed cases (on log10)",
    title = "Worldwide coronavirus confirmed cases",
    subtitle = "highlighting New Zealand",
    caption = "Data source: John Hopkins University, CSSE"
  )
p_nz
```

```{r interactive}
#make interactive
library(plotly)
ggplotly(p_nz)
```